### ISSUE TITLE
Integration with Next JS

### ISSUE THREAD

**Issue by damianlluch** [VGLoic/metamask-react#3] opened 2021-06-20 15:23 UTC
Hello, this project seems to be very good, do you know how I could integrate this library in a project with Next?

Thanks

**Comment by VGLoic** [comment] 2021-06-20 15:55
Hello! Thanks a lot!
As I understand the problem is the initial derivation of the state which uses the `window` object, so indeed it will not work in the current state with Next applications. I will work on a solution :)

**Comment by VGLoic** [comment] 2021-06-20 17:12
It should be fixed in version 2.0.2 :)
Here is a codesanbox: https://codesandbox.io/s/getting-started-with-next-forked-ijvjr?file=/pages/_app.js where Next is used. Please tell me if it does not solve your problem!

**Comment by damianlluch** [comment] 2021-06-20 20:14
Thank you very much @VGLoic , I'll give it a try

**Comment by VGLoic** [comment] 2022-01-09 11:39
Closing as no related problems have been raised :)

**Closed by VGLoic** 2022-01-09 11:39 UTC
