### ISSUE TITLE
Error not updating status

### ISSUE THREAD

**Issue by forgowhisky** [VGLoic/metamask-react#27] opened 2022-03-02 17:07 UTC
### What version of React and MetaMask-React are you using?

- React: 
- MetaMask-React:

### What is the current behavior?

When metamask is not logged in (in the browser via plugin), the status gets stuck at "connecting".

### What is the expected behavior?

I would expect this to update to "unavailable" or something else besides "connecting".

Maybe I am missing something but it does not seem as though I have a way to determine whether or not the user is logged in via metamask, aka that metamask is available.

**Comment by VGLoic** [comment] 2022-03-02 17:25
Hey @forgowhisky, thanks a lot for the issue!

Sorry, I'm not sure to picture well the flow in question! Did you trigger the `connect` method at some point? :)

How it (should) work currently is:

- `status` starts as `initializing`
- if MetaMask is not available at all, like in private navigation or on a Safari browser, the status will become `unavailable`,
- if MetaMask is available, either an account is connected, in this case the status will be `connected`, otherwise it will be `notConnected`.

If the `connect` methods is triggered, the status will switch to `connecting` until the user has dealt with the MetaMask connection popup (which is sometimes hidden but can be get from the little icon `1` in the MetaMask icon of the extension)

In terms of wording, the MetaMask "available" (`const isAvailable = status !== "unavailable" && status !== "initializing";`) defines whether or not the current browser instance comes with a MetaMask. The MetaMask "connected" defines whether or not the user's MetaMask has at least one account connected to the application

**Comment by forgowhisky** [comment] 2022-03-08 17:08
Yes, basically I dont know how to determine when metamask is installed in a browser (like chrome), but the user is NOT logged in to their metamask plugin.

I would assume the status would === 'unavailable'.

However, it actually === 'notConnected'.

The problem here, is I am unable to instruct a user to login to their metamask plugin because the app is unable to determine whether or not they are logged into their metamask plugin.

If a user is NOT logged in to their metamask plugin and I try to connect them, nothing happens at all.

**Comment by VGLoic** [comment] 2022-03-08 18:00
So for the statuses:
- MetaMask not installed in the browser is: `status === "unavailable"`,
- MetaMask installed in the browser but user not connected to the application is `status === "notConnected"`

However, your description indicates a bug if the user can not connect. I tried to find the issue on my side but I could not reproduce the issue unfortunately.

Do you have a codesandbox (or even a code snippet) with the problematic flow please? 🙏 It would greatly help me fix the potential issue :)

**Comment by forgowhisky** [comment] 2022-03-08 19:49
That seems to be the issue!
It gets stuck as status === 'connecting'

Here is a screen shot of me calling the connect() function several times in a row while not logged in to the metamask plugin.

(there is a hook to console log anytime the status updates, so as you see it gets stuck on connecting)

![image](https://user-images.githubusercontent.com/91902208/157313902-788ffa86-7b65-4828-bac4-8d407d83f31b.png)

**Comment by forgowhisky** [comment] 2022-03-08 19:51
After closing and trying again to produce similar results, it does not even change the status to notConnected or connecting.
Only says initializing and then errors.

I tried to wrap the connect function in a try catch so I could report to the user that they need to login but the catch never triggers.

Thus, it seems I have no way to tell a user that their metamask plugin is not logged in.

![image](https://user-images.githubusercontent.com/91902208/157314114-59cd0cd6-9354-444c-b53e-e9cd528a2651.png)

**Comment by VGLoic** [comment] 2022-03-08 20:30
Thanks for the logs! Could you please

1. tell me the version of metamask-react you are using (from package-lock or yarn.lock),
2. if you are not at the latest version (2.3.0), try with the latest version please (a fix has been done quite recently concerning pending connection: https://github.com/VGLoic/metamask-react/issues/13),
3. if the problem persist and if possible, fork and update the code of this codesandbox: https://codesandbox.io/s/status-problem-27-kxnn4s?file=/src/App.tsx in order to have a way for me to replicate the issue 🙏 
4. during the problematic flow, what are you doing of the MetaMask popup for the connection? :)

**Comment by forgowhisky** [comment] 2022-03-08 20:58
I was on 2.2.0

I will update and try again.

This may also solve my other issue I just opened.

**Comment by forgowhisky** [comment] 2022-03-08 21:03
I updated to 2.3.0 and both reported issues are still occurring.

I will look at your sandbox snippet and see if I can find a solution.

**Comment by forgowhisky** [comment] 2022-03-08 21:06
When I copy and paste your code directly, it does not work for me... I wonder why that could be?

![image](https://user-images.githubusercontent.com/91902208/157325017-c2b7f1cc-f6c9-4c63-9550-59961bd5fd96.png)

**Comment by forgowhisky** [comment] 2022-03-08 21:45
Update: after further testing with another dev I can report that:

- its SOMETIMES working for him as expected.
- Sometimes, he has to first visit the home page and then a page with the connect button to get it to work.
- And sometimes it doesnt ever work unless he manually logs into metamask and refreshes the page.

For me: it ALWAYS behaves as the last bullet point listed above.

**Comment by VGLoic** [comment] 2022-03-09 07:46
Okay let's try to find the cause of the issue

Could you try to find the extension which is responsible for the error `"Receiving end does not exist"` please? From what I found, it is related to chrome extensions, see [this video](https://www.youtube.com/watch?v=DsKYuBn7YpQ) in order to identify which extension is causing the issue

Otherwise, could you please tell me which browser you are using, its version and which MetaMask version you are using please? :)

**Comment by VGLoic** [comment] 2022-04-16 10:39
Closing for inactivity, feel free to reopen if there are new elements related to this!

**Closed by VGLoic** 2022-04-16 10:39 UTC
